version: "3.7"
services:

  php:
    build:
      args:
        user: app
        uid: ${USER_UID}
      context: ./
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/app
      - /app/vendor
    networks:
      - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - ./.docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - php
    networks:
      - backend

  node:
    build:
      args:
        user: app
        uid: ${USER_UID}
      context: ./
      dockerfile: .docker/node/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules

networks:
  backend:
