version: "3.7"
services:

  php:
    build:
      args:
        user: app
        uid: 1000
      context: ./
      dockerfile: .docker/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_HOST: ${DB_HOST}
    volumes:
      - ./:/app
      - /app/vendor
    networks:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - backend

  node:
    image: node:latest
    volumes:
      - ./:/app
    networks:
      - backend
    command: ["npm", "prod"]

networks:
  backend:
